### PR TITLE
Improve UI for tftpd (fix issue #5)

### PR DESCRIPTION
**Pull request by bjoernalbers**
There it is again :-)

### CODE REVIEW

**Comment by bjoernalbers** [comment]
@drbig Travis is happy again B-)

**Comment by drbig** [comment]
Very nice :) Will look this over the weekend. Thank you again!

**Comment by bjoernalbers** [comment]
@drbig Please do not pull yet. I've notices a bug which I want to fix first. Thanks

**Comment by drbig** [comment]
I will sit on this sooner or later :)

**Comment by bjoernalbers** [comment]
Nice. I did some testing today: it works so far.

**Pull request merged**
